services:
  - type: web
    name: senti-app
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: senti-db
          property: connectionString

    # ‚≠ê THIS PART RUNS YOUR MIGRATIONS AUTOMATICALLY
    releaseCommand: flask db upgrade

databases:
  - name: senti-db
    region: oregon